server:
  port: 10001

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/donate-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: xxxxxxxx
  redis:
    # Redis 单机单实例
    host: redis
    port: 6379
    database: 0
    password: xxxxxxxx

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

hystrix:
  command:
    # 有的属性是默认值，写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误，那么开启熔断
        errorThresholdPercentage: 50
        # 5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed, forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式是线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          # 时间窗口统计
          timeInMilliseconds: 20000

    # 针对登录的fallback方法的单独配置，优先级最高
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
