server:
  port: 10004

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/donate-order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: xxxxxxxx
  redis:
    # Redis 单机单实例
    host: redis
    port: 6379
    database: 0
    password: xxxxxxxx

  rabbitmq:
    host: rabbitmq # rabbitmq配置
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    delivery:
      exchange:
        name: delivery-exchange
        key: delivery.1

# seata

seata:
  service:
    vgroup-mapping:
      seata-order: default
    grouplist:
      default: seata-server:8091

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出具体sql

# Ribbon全局配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000

# Feign的超时判定，优先级高于Ribbon
feign:
  hystrix:
    enabled: true
  client:
    config:
      # 全局默认配置
      default:
        connectTimeout: 1000
        readTimeout: 5000

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


